#!/bin/sh
# DESCRIPTION: A screenshot utility using dmenu.
# DEPENDENCIES: bspc(bspwm) maim mktemp notify-send sxiv xclip xdotool
get_filename ()
{
	echo "$HOME/Pictures/screenshot-$(date +%Y-%m-%dT%H:%M:%S).png"
}

do_window ()
{
	maim --window $(xdotool getactivewindow)
}
do_screen ()
{
	maim
}
do_selection ()
{
	maim --select
}

# Set up sxiv for viewing a file in floating mode.
# NOTE: removes *all* simple bspwm rules for sxiv.
sxiv_view_floating ()
{
	bspc rule -a 'Sxiv:*' --one-shot state=floating
	sxiv -p "$1" &
	# We want sxiv to see the image before we do clean up, since
	# "$1" might be the tempfile to be deleted soon.
	sleep 2
}

options='
window
screen
selection
'
dests='
clipboard
file
fileview
tempview
'
opt="$(echo "$options" | sed '1d; $d' | dmenu -i -p 'What kind of screenshot?')" || exit 1
err=0
case "$opt" in
	window|screen|selection)
		f="$(mktemp)"
		cmd=do_$opt
		dest="$(echo "$dests" | sed '1d; $d' | dmenu -i -p 'Save where?')" || exit 1
		if $cmd > "$f"; then
			case "$dest" in
				clipboard)
					xclip -selection clipboard -target image/png < "$f"
					notify-send -t 500 'Screenshot saved to clipboard'
					;;
				# Save into file, optionally viewing it at the same time.
				file|fileview)
					realf="$(get_filename)"
					if mv "$f" "$realf"; then
						notify-send -t 2000 "Screenshot saved to '$realf'"
						if [ "$dest" = fileview ]; then
							sxiv_view_floating "$realf"
						fi
					else
						notify-send -t 5000 -u critical "dmenu_screenshot: failed to save screenshot" "Tried to save to '$realf' but mv failed"
						err=1
					fi
					;;
				# View the screenshot without saving it.
				tempview)
					sxiv_view_floating "$f"
					;;
				*)
					notify-send -t 5000 -u critical \
						"dmenu_screenshot: invalid destination" \
						"Got '$dest' but should be one of '$(echo "$dests" | sed '1d; $d' | tr '\n' ' ' | sed 's/ $//')'"
					err=1
					;;
			esac
		else
			notify-send -t 5000 -u critical "dmenu_screenshot: maim failed or saving to tempfile failed"
			err=1
		fi
		rm -f "$f"
		;;
	*)
		notify-send -t 5000 -u critical \
			"dmenu_screenshot: invalid option" \
			"Got '$opt' but should be one of '$(echo "$options" | sed '1d; $d' | tr '\n' ' ' | sed 's/ $//')'"
		err=1 ;;
esac
[ "$err" -ne 0 ] && exit "$err"
