#!/bin/sh
option="$(cat <<EOF | dmenu -i -p 'What power operation?'
logout
suspend
hibernate
shutdown
restart
EOF
)" || exit 1

sure="$(printf 'no\nyes\n' | dmenu -i -p "$option: Are you sure?")" || exit 1
[ "$sure" != yes ] && exit 1

case "$option" in
	logout)
		notify-send -t 5000 -u critical 'Logging out...'
		bspc quit
		;;
	suspend)
		notify-send -t 5000 -u critical 'Suspending to RAM...'
		systemctl suspend
		;;
	hibernate)
		notify-send -t 5000 -u critical 'Suspending to disk...'
		systemctl hibernate
		;;
	shutdown)
		notify-send -t 5000 -u critical 'Shutting down...'
		systemctl poweroff
		;;
	restart)
		notify-send -t 5000 -u critical 'Restarting...'
		systemctl reboot
		;;
esac

