#!/bin/sh
# DESCRIPTION: View keybinds of my specially formatted sxhkdrc in dmenu (for keybinds and their descriptions) and zenity (keybind bodies).
# DEPENDENCIES: dmenu zenity
: "${XDG_CONFIG_HOME:=$HOME/.config}"
conf="$XDG_CONFIG_HOME/sxhkd/sxhkdrc"
keybind="$(awk -v OFS='\t' '
# Commented, CAPS section names for easy partitioning.  "=" prefix.
/^#[[:space:]]+[[:upper:]][A-Z./ +<>-]+:$/ {match($0, "[[:upper:]][A-Z./ +<>-]+"); section=substr($0, RSTART, RLENGTH); print "=" section; next}

# Commented, Titled-cased first word description of the keybind on the following line.
/^#[[:space:]]+[[:upper:]].*\.$/{sub("^#[[:space:]]+",""); description=$0; new_desc=1; next}

# The actual keybind, which is the line *immediately after* its description.
{if(new_desc) {print description, $0; new_desc=0}}' "$conf" | dmenu -i -l 20 -p 'View keybind:' | cut -d'	' -f2-)"

case "$keybind" in
	=*|'') : ;;
	*)
		keybind_body_start_line="$(( $(grep -Fxn "$keybind" "$conf" | head -n 1 | cut -d: -f1) + 1 ))"
		sed -n "$keybind_body_start_line,/^[^\\t]/p" "$conf" | awk '/^\t/{sub("^\t",""); print}' | zenity --title="Body for '$keybind' keybind" --text-info
		;;
esac
