#!/bin/bash
export IN_DMENU_SURFRAW=yes

me=dmenu_surfraw

case "$DO_FIELD_SPLIT" in
	yes|no) ;;
	*) notify-send -t 1000 "$me: must set \$DO_FIELD_SPLIT to (yes|no)"; exit 1 ;;
esac

source surfraw
elvi=($(cd "$(get_local_elvi_dir)" 2>/dev/null && echo *
	cd "$elvidir" 2>/dev/null && echo *))
bookmarks=($(cut -f1 "$(find_local_conf bookmarks)" "$(find_global_conf bookmarks)" 2>/dev/null))

END_MANY_SELECT=DONE

# Determine elvis:
elvis_exists ()
{
	for el in "${elvi[@]}" "${bookmarks[@]}"; do
		if [ "$1" = "$el" ]; then
			return 0
		fi
	done
	return 1
}
elvis="$(echo "${elvi[@]}" "${bookmarks[@]}" | tr ' ' '\n' | dmenu -p 'Elvis?')" || exit 1  # back out.
if [[ -z "$elvis" ]]; then
	notify-send -t 1000 "$me: empty elvis"
	exit 1
elif ! elvis_exists "$elvis" ; then
	notify-send -t 1000 "$me: '$elvis' doesn't exist"
	exit 1
fi

# Plain args:
#do_field_split="$(printf 'yes\nno\n' | dmenu -p 'Do field splitting on query?')" || exit 1
#do_accept_completions="$(printf 'yes\nno\n' | dmenu -p 'Accept completions?')" || exit 1

get_arg ()
{
	local prompt
	prompt="$1"
	{ echo "--${END_MANY_SELECT}--"; surfraw "$elvis" -complete-arg=; } | dmenu -p "$prompt"
}
ARGS=()
case "$DO_FIELD_SPLIT" in
	yes)
		arg="$(get_arg 'Query?')" || exit 1
		# Do field splitting.
		[[ $arg != "--${END_MANY_SELECT}--" ]] && ARGS+=($arg)
		;;
	no)
		n=1
		arg="$(get_arg "Query arg ${n}?")" || exit 1
		while [[ $arg != "--${END_MANY_SELECT}--" ]]; do
			ARGS+=("$arg")
			n=$(( n + 1 ))
			arg="$(get_arg "Query arg ${n}?")" || exit 1
		done
		;;
	*) exit 1 ;;
esac

# Options + their args (if any):
get_opt ()
{
	{ echo "$END_MANY_SELECT"; surfraw "$elvis" -complete=-; } |
		sed -e 's/^ //g' -e 's/ $//g' |
		tr ' ' '\n' |
		dmenu -p 'Option?'
}

OPTIONS=()
opt=$(get_opt) || exit 1
while [[ $opt != $END_MANY_SELECT ]]; do
	case "$opt" in
		-*=)
			arg=$(surfraw "$elvis" -complete="$opt" | tr ' ' '\n' | dmenu -p "Arg to '$opt'?") || { opt=$(get_opt) && continue || exit 1; }
			OPTIONS+=("$opt$arg")
			;;
		*)
			OPTIONS+=("$opt")
			;;
	esac

	opt=$(get_opt) || exit 1
done

# Finally, open browser:
exec surfraw -graphical "$elvis" "${OPTIONS[@]}" -- "${ARGS[@]}"
