#!/bin/sh
# Open surfraw bookmark interactively in a graphical browser
. surfraw || exit 1
bookmark="$(cat "$(find_local_conf bookmarks)" "$(find_global_conf bookmarks)" | fzf | cut -f 1)"
[ -n "$bookmark" ] && exec surfraw -graphical -- "$bookmark"
