#!/bin/sh
# Merge two PDFs (one for each side) to look like it was a double-sided scan.
usage ()
{
	cat <<'EOF'
Usage: merge-double-sided-scan [--help | --reverse] file file
Merge two PDFs (one for each side) to look like it was a double-sided scan.

Options:
  --help, -h		View this help message
  --reverse, -r	Reverse the pages of the second file
EOF
}

f2_pagerange="1-z"
case "$1" in
	--help|-h) usage; exit ;;
	--reverse|-r) f2_pagerange="z-1"; shift ;;
esac

[ -z "$1" ] && { echo "first file argument missing" >&2; exit 1; }
[ -z "$2" ] && { echo "second file argument missing" >&2; exit 1; }
f1="$1"
f2="$2"

qpdf --collate --empty --pages "$f1" "$f2" "$f2_pagerange" -- out.pdf
