#!/bin/sh
# DESCRIPTION: chord watcher for sxhkcd to use in indicating mode in wm
# DEPENDENCIES: ...
# ARGUMENTS:
#   $1: fifo that sxhkd writes its status info to
#   $2: fifo to write bspwm's mode into

MODE_RESIZE='mod4 + r'
MODE_MOVE_FLOATING='mod4 + shift + f'

first_seen=1 # can't seem to rely on sequencing of B* and H* for chords
mode=normal
echo "$mode" > "$2"
while read line; do
	case "$line" in
		B*)
			notify-send -t 500 "Began chord chain"
			;;
		# Complete or time-out of chord chain
		E*|T*)
			notify-send -t 500 "Finished chord chain"
			first_seen=1
			mode=normal
			echo "$mode" > "$2"
			;;
		# These chain keybinds are unable to conflict with non-chains
		?"$MODE_RESIZE"*|?"$MODE_MOVE_FLOATING"*)
			if [ "$first_seen" = 1 ]; then
				first_seen=0
				case "$line" in
					?"$MODE_RESIZE"*) mode=resize ;;
					?"$MODE_MOVE_FLOATING"*) mode=move_floating ;;
				esac
				echo "$mode" > "$2"
			fi
			;;
		# TODO: do something with commands (C*).
		C*|*)   :
			;;
	esac
done < "$1"
