#!/bin/sh
# DESCRIPTION: Repeatedly get weather forecast from wttr.in without `watch`
# DEPENDENCIES: curl
# The reason for *not* using `watch` is because, although the ANSI escapes are processed by `watch`,
# no colour is actually output.

# In minutes; 1 hour default.
WATCH_INTERVAL="$(( ${WATCH_INTERVAL:-60} * 60 ))"
WTTR_LOCATION=Auckland

do_header ()
{
	clear
	printf 'watch_weather: every %d mins | fetched on %s\n' "$WATCH_INTERVAL" "$(date)"
}

do_header
curl --silent --show-error wttr.in/"$WTTR_LOCATION"
while sleep "$WATCH_INTERVAL"; do
	do_header
	curl --silent --show-error wttr.in/"$WTTR_LOCATION"
done
