#!/bin/sh
# DESCRIPTION: A desktop magnification utility.
# DEPENDENCIES: notify-send slop xzoom

notify-send -t 2000 'Zoom Tool' 'Select a region to zoom'
selection="$(slop)" || exit 1
exec xzoom -source "$selection"
